# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31c817cf9c417614c1aaaea4c7ffeba3b8955fd381796bd3e3f96de6c48efc7fa41a456324fdbd1afb2adf83b186b51e883bb2cf0a02266339fded4e278be16c

test:
  secret_key_base: 2424f7bc55dcf7e62713fb28a7c56919e9810e17f2f040e7c87406668df6fec86c55a1588c97c9b16eda7d7b4599636e92fcbc7b7e4fd13f4b0e920758f24a6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
