menubar : false
toolbar: formatselect | bold italic | bullist numlist |forecolorpicker forecolor | link unlink | code |fullscreen | font[size|color|style]
oninit : "setPlainText"
forced_root_block : false
plugins:
  - paste
  - code
  - link
setup :
  function(ed) {
    ed.on('init', function() 
    {
        this.getDoc().body.style.fontSize = '16px';
    });
  }
